// <auto-generated />
using System;
using AzureSuite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureSuite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902081347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureSuite.Domain.Entities.Pacs008Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RemittanceInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Pacs008Messages");
                });

            modelBuilder.Entity("AzureSuite.Domain.Entities.Pacs008Message", b =>
                {
                    b.OwnsOne("AzureSuite.Domain.ValueObjects.PartyAccount", "Creditor", b1 =>
                        {
                            b1.Property<Guid>("Pacs008MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BicCode")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("CreditorBic");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasMaxLength(34)
                                .HasColumnType("nvarchar(34)")
                                .HasColumnName("CreditorIban");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(140)
                                .HasColumnType("nvarchar(140)")
                                .HasColumnName("CreditorName");

                            b1.HasKey("Pacs008MessageId");

                            b1.ToTable("Pacs008Messages");

                            b1.WithOwner()
                                .HasForeignKey("Pacs008MessageId");
                        });

                    b.OwnsOne("AzureSuite.Domain.ValueObjects.PartyAccount", "Debtor", b1 =>
                        {
                            b1.Property<Guid>("Pacs008MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BicCode")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("DebtorBic");

                            b1.Property<string>("Iban")
                                .IsRequired()
                                .HasMaxLength(34)
                                .HasColumnType("nvarchar(34)")
                                .HasColumnName("DebtorIban");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(140)
                                .HasColumnType("nvarchar(140)")
                                .HasColumnName("DebtorName");

                            b1.HasKey("Pacs008MessageId");

                            b1.ToTable("Pacs008Messages");

                            b1.WithOwner()
                                .HasForeignKey("Pacs008MessageId");
                        });

                    b.Navigation("Creditor")
                        .IsRequired();

                    b.Navigation("Debtor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
