using AzureSuite.Domain.Entities;
using AzureSuite.Domain.Enums;
using AzureSuite.Domain.ValueObjects;
using FluentAssertions;

namespace AzureSuite.Domain.Tests.Entities;

public class Pacs008MessageTests
{
    private static Pacs008Message CreateMessage() => new()
    {
        MessageId = "MSG-0001",
        EndToEndId = "E2E-0001",
        Amount = 100.50m,
        Currency = "EUR",
        Debtor = new PartyAccount { Name = "Alice", Iban = "DE89370400440532013000", BicCode = "COBADEFFXXX" },
        Creditor = new PartyAccount { Name = "Bob", Iban = "FR1420041010050500013M02606", BicCode = "PSSTFRPPXXX" }
    };

    [Fact]
    public void Id_IsAutoGenerated_WhenNotExplicitlySet()
    {
        var message = CreateMessage();

        message.Id.Should().NotBeEmpty();
    }

    [Fact]
    public void Status_DefaultsToReceived()
    {
        var message = CreateMessage();

        message.Status.Should().Be(MessageStatus.Received);
    }

    [Fact]
    public void ReceivedAt_DefaultsToUtcNow_WhenNotExplicitlySet()
    {
        var before = DateTimeOffset.UtcNow;

        var message = CreateMessage();

        var after = DateTimeOffset.UtcNow;
        message.ReceivedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void RemittanceInformation_IsOptional()
    {
        var message = CreateMessage();

        message.RemittanceInformation.Should().BeNull();
    }

    [Fact]
    public void Status_CanTransition_ToProcessed()
    {
        var message = CreateMessage();

        message.Status = MessageStatus.Processed;

        message.Status.Should().Be(MessageStatus.Processed);
    }
}
