using AzureSuite.Domain.Entities;
using FluentAssertions;

namespace AzureSuite.Domain.Tests.Entities;

public class UserTests
{
    [Fact]
    public void Id_IsAutoGenerated_WhenNotExplicitlySet()
    {
        var user = new User { Email = "test@example.com", PasswordHash = "hash" };

        user.Id.Should().NotBeEmpty();
    }

    [Fact]
    public void Id_IsUnique_AcrossInstances()
    {
        var first = new User { Email = "a@example.com", PasswordHash = "hash" };
        var second = new User { Email = "b@example.com", PasswordHash = "hash" };

        first.Id.Should().NotBe(second.Id);
    }

    [Fact]
    public void CreatedAt_DefaultsToUtcNow_WhenNotExplicitlySet()
    {
        var before = DateTimeOffset.UtcNow;

        var user = new User { Email = "test@example.com", PasswordHash = "hash" };

        var after = DateTimeOffset.UtcNow;
        user.CreatedAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void Email_And_PasswordHash_AreSettableAfterConstruction()
    {
        var user = new User { Email = "initial@example.com", PasswordHash = "initial-hash" };

        user.Email = "updated@example.com";
        user.PasswordHash = "updated-hash";

        user.Email.Should().Be("updated@example.com");
        user.PasswordHash.Should().Be("updated-hash");
    }
}
